/* Question Action Types */

export const DELETE_QUESTION = "DELETE_QUESTION";
export const CREATE_QUESTION = "CREATE_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const SET_ALL_QUESTIONS = "SET_ALL_QUESTIONS";
export const SET_USER_QUESTIONS = "SET_USER_QUESTIONS";
export const ADD_A_QUESTION = "ADD_A_QUESTION";
export const REVIEW_QUESTION = "REVIEW_QUESTION";
export const ANSWER_A_QUESTION = "ANSWER_A_QUESTION";
export const GET_SINGLE_QUESTION = "GET_SINGLE_QUESTION";
